/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_authentication.h"

bool_t
xdr_operation_status_t (XDR *xdrs, operation_status_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_authorization_response (XDR *xdrs, request_authorization_response *objp)
{
	register int32_t *buf;

	 if (!xdr_operation_status_t (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->authorization_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_token_request (XDR *xdrs, access_token_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->authorization_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->autorefresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_token_response (XDR *xdrs, access_token_response *objp)
{
	register int32_t *buf;

	 if (!xdr_operation_status_t (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->token_expiration))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_request (XDR *xdrs, validate_delegated_action_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->operation_type, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->accessed_resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_response (XDR *xdrs, validate_delegated_action_response *objp)
{
	register int32_t *buf;

	 if (!xdr_operation_status_t (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_token_request (XDR *xdrs, refresh_token_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_token_response (XDR *xdrs, refresh_token_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->new_access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->new_refresh_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->token_expiration))
		 return FALSE;
	return TRUE;
}
